version: 2.1
machine:
  services: docker
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker: 
          version: 19.03.13
      - run: docker run s4sarang/reactapp npm run test -- --coverage

workflows:
  example-workflow:
    jobs:
      - build
